### ISSUE TITLE
fix : 고객센터 기능 수정

### ISSUE THREAD

**Issue by Choding91** [A7-TC2-TeamCode200/MRLA_Front#11]
- 등록한 게시글이 상단에서부터 출력되지 않고 중앙에서부터 출력되는 문제 해결 필요

**Comment by Choding91** [comment]
등록된 게시글 제목 글자 수 초과 시 생략(...) 표기되지 않는 문제 해결 필요

**Comment by Taeeun99** [comment]
고객센터에 문의하는 화면 깨짐과 글자수 제한이 필요

**Comment by Taeeun99** [comment]
css깨짐 및, 불필요한 정보  제거, 색 통일 필요
