### ISSUE TITLE
Feat : "누구랑 먹나요?" 페이지 구현 

### ISSUE THREAD

**Issue by Taeeun99** [A7-TC2-TeamCode200/MRLA_Front#7]
Feat : "누구랑 먹나요?" 페이지 구현

**Comment by ja2w0nii** [comment]
- [ ] 함께 식사할 대상(Food 모델의 target 필드) 카테고리 : 가족, 연인, 친구, 직장 동료, 혼밥
- [ ] 함께 식사할 대상에 맞춰 메뉴 추천 기능 구현
