### ISSUE TITLE
Feat: 메뉴(음식) 디테일 페이지 구현

### ISSUE THREAD

**Issue by R5Z** [A7-TC2-TeamCode200/MRLA_Front#9]
- 메뉴(음식) 클릭 시 조회할 수 있는 디테일 페이지
- [x] 페이지 생성
- [x] 메뉴 이미지와 이름 조회
- [x] 좋아요 버튼 활성화
- 댓글 
- [x] 조회
- [x] 작성
- [x] 수정
- [x] 삭제

**Comment by R5Z** [comment]
! Unauthorized:
인증 오류가 있습니다. views.py/foods 의 메뉴 상세 페이지, 메뉴에 대한 댓글 curd 부분 permissions 주석 처리 후 진행한 상황입니다.

**Comment by Choding91** [comment]
@R5Z 내용은 이미 전달드렸지만, 추후 트러블 슈팅 작성 시 하기 내용 참고하시면 좋을 듯합니다.

문제 코드
"Authorization": "Bearer" + localStorage.getItem("access")

해결 방법
Authorization: "Bearer " + localStorage.getItem("access")
"Authorization" > Authorization (큰따옴표 제거)
"Bearer" > "Bearer " (띄어쓰기 추가)

**Comment by R5Z** [comment]
> ! Unauthorized: 인증 오류가 있습니다. views.py/foods 의 메뉴 상세 페이지, 메뉴에 대한 댓글 curd 부분 permissions 주석 처리 후 진행한 상황입니다.

해결되었습니다. Bearer 뒤 스페이스바 누락. "Bearer" > "Bearer " 로 해결
